spring:
  application:
    name: bulk-service-scheduler
  cloud:
    gcp:
      project-id: YOUR-GCP-PROJECT-ID-HERE
      bigquery:
        dataset-name: bulk_status
      sql:
        database-name: bulk-status-db
        instance-connection-name: YOUR-GCP-PROJECT-ID-HERE:europe-west2:bulk-status-instance
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org:
        quartz:
          jobStore: 
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
          threadPool:
            threadCount: 5
  datasource:
    username: YOUR-DATABASE-USER
    password: YOUR-DATABASE-PASSWORD
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
    enabled-by-default: false
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
logging:
  level:
    root: INFO
    uk:
      gov:
        ons: INFO
aims:
  pubsub:
    subscription: processing-finished-subscription
    export-topic: bulk-scheduler-export
  scheduler:
    frequency-minutes: 5